apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: hello
spec:
  containers:
    - name: web
      image: johnwang412/kube-hello
      ports:
        - containerPort: 12046
          name: http
          protocol: TCP

