apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: hello
spec:
  selector:
    name: web
  # NodePort picks a random port on one of the minikube environment nodes to
  #   open up and listen for connections to the hello service
  type: NodePort
  ports:
   - port: 8888
     targetPort: 12046
     protocol: TCP

